version: '3.7'
services:
  python:
    container_name: task_flow
    image: python/python:3.9-buster
    volumes:
      - ../:/home
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - metabase
      - database_admin
    volumes:
      - ./nginx:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: database
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: database
    restart: always
    hostname: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: postgres
    ports:
      - 3030:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
  database_admin:
    image: dpage/pgadmin4
    container_name: database_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: dbt
    volumes:
      - ./data:/data
      - ./dbt:/dbt_init
    command: /bin/bash -c "chmod +x /dbt_init/dbt_entrypoint.sh && /dbt_init/dbt_entrypoint.sh"
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    links:
      - database
    depends_on:
      - database

volumes:
  db-data:
