version: '3.7'
services:
  python:
    container_name: task_flow
    image: python/python:3.9-buster
    volumes:
      - ../:/home
  fastapi:
    container_name: fastapi
    image: nginx/unit:1.22.0-python3.9
    ports:
      - 80:80
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: '${MB_DB_DBNAME}'
      MB_DB_PORT: '${MB_DB_PORT}'
      MB_DB_USER: '${MB_DB_USER}'
      MB_DB_PASS: '${POSTGRES_PASSWORD}'
      MB_DB_HOST: '${MB_DB_HOST}'
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: database
    restart: always
    hostname: database
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 3030:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
  database_admin:
    image: dpage/pgadmin4
    container_name: database_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
      PGADMIN_LISTEN_PORT: '${PGADMIN_LISTEN_PORT}'
    ports:
      - 5050:80
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: dbt
    volumes:
      - ./data:/data
      - ./dbt:/dbt_init
    command: /bin/bash -c "chmod +x /dbt_init/dbt_entrypoint.sh && /dbt_init/dbt_entrypoint.sh"
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      - database

volumes:
  db-data:
